server:
  port: 30800
eureka:
  server:
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
    #启用主动失效，并且每次主动失效检测间隔为3s，默认60s
    eviction-interval-timer-in-ms: 3000
    #关闭自我保护=false
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    #eureka client刷新本地缓存时间，默认30s
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
#eureka客户端ribbon刷新时间，#默认30s
ribbon.ServerListRefreshInterval: 1000
