server:
  port: 30101

spring:
  application:
    name: greeting-service

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:30800/eureka/
    #eureka client刷新本地缓存时间，默认30s
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
#eureka客户端ribbon刷新时间，#默认30s
ribbon.ServerListRefreshInterval: 1000